// Festival data — acts, programming, stages, info
// Uses NL primary with EN translations

const STAGES = [
  { id: 'ponton', name: 'Ponton', short: 'PON', img: 'assets/ponton.png', color: '#E5352B',
    descNL: 'Het openluchtpodium aan het water. De plek voor grote optredens onder de open hemel.',
    descEN: 'The open-air waterside stage. Home to the headline performances under the open sky.' },
  { id: 'lake', name: 'The Lake', short: 'LAK', img: 'assets/lake.png', color: '#2B3BE5',
    descNL: 'Drijvend podium midden op het water. Dans met je voeten in het zand.',
    descEN: 'Floating stage on the lake. Dance with your feet in the sand.' },
  { id: 'club', name: 'The Club', short: 'CLB', img: 'assets/club.png', color: '#E5A52B',
    descNL: 'Intiem, warm, elektronisch. Palmen en pulserende beats tot diep in de nacht.',
    descEN: 'Intimate, warm, electronic. Palms and pulsing beats deep into the night.' },
  { id: 'hangar', name: 'Hangar', short: 'HNG', img: 'assets/hangar.png', color: '#ffffff',
    descNL: 'Industriële dome met 360° licht en geluid. Pure rave-energie.',
    descEN: 'Industrial dome with 360° light and sound. Pure rave energy.' },
];

const ACTS = [
  { id: 'armin', name: 'Armin van Buuren', tag: 'Trance legend', img: 'assets/act_armin.png',
    bioNL: 'Vijfvoudig DJ Mag #1 en trance-pionier. Armin brengt zijn A State of Trance-ervaring naar het Ponton met een tweeuurs peak-time set.',
    bioEN: 'Five-time DJ Mag #1 and trance pioneer. Armin brings his A State of Trance experience to the Ponton with a two-hour peak-time set.',
    genre: 'Trance' },
  { id: 'martin', name: 'Martin Garrix', tag: 'EDM producer', img: 'assets/act_martin.png',
    bioNL: 'Nederlandse topproducer met wereldhits als Animals en Scared to Be Lonely. Verwacht grote drops en pyro.',
    bioEN: 'Dutch super-producer behind worldwide hits like Animals and Scared to Be Lonely. Expect huge drops and pyro.',
    genre: 'EDM' },
  { id: 'kensington', name: 'Kensington', tag: 'Rock anthems', img: 'assets/act_kensington.png',
    bioNL: 'Utrechtse rockband die stadions vol krijgt. Hymnen om je stem kwijt te raken.',
    bioEN: 'Utrecht rock band filling stadiums. Anthems to lose your voice to.',
    genre: 'Rock' },
  { id: 'within', name: 'Within Temptation', tag: 'Symphonic metal', img: 'assets/act_within.png',
    bioNL: 'Sinds 1996 de belichaming van Nederlandse symfonische metal. Theatraal, episch, meeslepend.',
    bioEN: 'Since 1996 the embodiment of Dutch symphonic metal. Theatrical, epic, enveloping.',
    genre: 'Metal' },
  { id: 'destaat', name: 'De Staat', tag: 'Art rock', img: 'assets/act_destaat.png',
    bioNL: 'Onvoorspelbare art-rock uit Nijmegen. Torre Florim en z\'n band zoeken de rand op — altijd.',
    bioEN: 'Unpredictable art-rock from Nijmegen. Torre Florim and his band always push the edge.',
    genre: 'Art rock' },
  { id: 'chef', name: "Chef'Special", tag: 'Pop / hip-hop', img: 'assets/act_chef.png',
    bioNL: 'Haarlemse feestmakers. Reggae, pop en hip-hop smelten samen tot zomerhits zoals In Your Arms.',
    bioEN: 'Haarlem party starters. Reggae, pop and hip-hop blend into summer hits like In Your Arms.',
    genre: 'Pop' },
  { id: 'nienke', name: 'Nienke', tag: 'Indie folk', img: 'assets/act_nienke.png',
    bioNL: 'Fluisterzachte indie folk. Akoestische gitaar, eerlijke teksten en kippenvelmomenten.',
    bioEN: 'Whisper-soft indie folk. Acoustic guitar, honest lyrics and goosebump moments.',
    genre: 'Folk' },
  { id: 'distan', name: 'Distan', tag: 'Alt pop', img: 'assets/act_distan.png',
    bioNL: 'Dromerige alt-pop met donkere synths en een onverwachte stem.',
    bioEN: 'Dreamy alt-pop with dark synths and an unexpected voice.',
    genre: 'Alt pop' },
  { id: 'sofia', name: 'Sofia de Visser', tag: 'Singer-songwriter', img: 'assets/act_sofia.png',
    bioNL: 'Intieme nummers over verlies en hoop. Een stem die je stil maakt.',
    bioEN: 'Intimate songs about loss and hope. A voice that silences the room.',
    genre: 'Singer-songwriter' },
  { id: 'prodeje', name: 'Prodeje', tag: 'Hip-hop', img: 'assets/act_prodeje.png',
    bioNL: 'Scherpe flows en zware beats. Een van de meest opwindende nieuwe stemmen uit de scene.',
    bioEN: 'Sharp flows and heavy beats. One of the most exciting new voices on the scene.',
    genre: 'Hip-hop' },
  { id: 'splash', name: 'Splash', tag: 'Performance', img: 'assets/act_splash.png',
    bioNL: 'Vijf performers, oneindige energie. Een visuele show op het raakvlak van dans, theater en muziek.',
    bioEN: 'Five performers, endless energy. A visual show at the intersection of dance, theatre and music.',
    genre: 'Performance' },
];

// Programme — block schedule. Saturday (day 1) + Sunday (day 2)
// stageId, actId, start hour (decimal, 13 = 13:00), duration hours
const SCHEDULE = {
  saturday: [
    // Ponton
    { stageId: 'ponton', actId: 'destaat', start: 14, end: 15 },
    { stageId: 'ponton', actId: 'kensington', start: 16, end: 17.5 },
    { stageId: 'ponton', actId: 'chef', start: 18.5, end: 20 },
    { stageId: 'ponton', actId: 'within', start: 21, end: 22.5 },
    { stageId: 'ponton', actId: 'armin', start: 23, end: 25 },
    // Lake
    { stageId: 'lake', actId: 'nienke', start: 13, end: 14 },
    { stageId: 'lake', actId: 'sofia', start: 15, end: 16 },
    { stageId: 'lake', actId: 'distan', start: 17, end: 18 },
    { stageId: 'lake', actId: 'splash', start: 19, end: 20 },
    { stageId: 'lake', actId: 'prodeje', start: 21, end: 22 },
    // Club
    { stageId: 'club', actId: 'distan', start: 20, end: 21.5 },
    { stageId: 'club', actId: 'martin', start: 22, end: 24 },
    { stageId: 'club', actId: 'armin', start: 1, end: 3 },
    // Hangar
    { stageId: 'hangar', actId: 'prodeje', start: 22, end: 23.5 },
    { stageId: 'hangar', actId: 'martin', start: 0.5, end: 2.5 },
  ],
  sunday: [
    { stageId: 'ponton', actId: 'nienke', start: 13, end: 14 },
    { stageId: 'ponton', actId: 'sofia', start: 14.5, end: 15.5 },
    { stageId: 'ponton', actId: 'within', start: 17, end: 18.5 },
    { stageId: 'ponton', actId: 'chef', start: 20, end: 21.5 },
    { stageId: 'ponton', actId: 'martin', start: 22.5, end: 24 },
    { stageId: 'lake', actId: 'destaat', start: 14, end: 15 },
    { stageId: 'lake', actId: 'kensington', start: 16, end: 17 },
    { stageId: 'lake', actId: 'splash', start: 18, end: 19 },
    { stageId: 'lake', actId: 'prodeje', start: 20, end: 21 },
    { stageId: 'club', actId: 'distan', start: 19, end: 20.5 },
    { stageId: 'club', actId: 'armin', start: 22, end: 24 },
    { stageId: 'hangar', actId: 'martin', start: 20, end: 22 },
    { stageId: 'hangar', actId: 'prodeje', start: 23, end: 25 },
  ],
};

const I18N = {
  nl: {
    home: 'Home', lineup: 'Line-up', map: 'Plattegrond', info: 'Info', favs: 'Favorieten',
    welcome: 'Welkom op',
    festival: '❤️U Festival 2026',
    date: 'za 5 & zo 6 september',
    location: 'Strijkviertel, Utrecht',
    stagesHeader: 'Podia',
    upNext: 'Komt eraan',
    favHeader: 'Jouw favorieten',
    noFavs: 'Nog geen favorieten. Tik op een hart om acts te volgen.',
    saturday: 'Zaterdag', sunday: 'Zondag',
    now: 'Nu',
    startsIn: 'Begint over',
    notify: 'Herinnering aan',
    legend: 'Legenda',
    entrance: 'Entree / Uitgang', toilet: 'Toilet', food: 'Eten & Drinken',
    firstaid: 'EHBO', info_pt: 'Info', lockers: 'Lockers', water: 'Water', smoke: 'Rookzone',
    faq: 'Veelgestelde vragen',
    contact: 'Algemeen & contact',
    reach: 'Bereikbaarheid',
    lockers_h: 'Lockers',
    golden: 'Golden-GLU',
    min: 'min', hour: 'u',
    favAdded: 'Toegevoegd aan favorieten',
    notifOn: 'Meldingen aan: 15, 10 en 5 min voor aanvang',
    backToLineup: 'Terug naar line-up',
    readMore: 'Lees meer',
    watchClip: 'Bekijk clip',
    stage: 'Podium', genre: 'Genre', time: 'Tijd', duration: 'Duur',
  },
  en: {
    home: 'Home', lineup: 'Line-up', map: 'Map', info: 'Info', favs: 'Favorites',
    welcome: 'Welcome to',
    festival: '❤️U Festival 2026',
    date: 'Sat 5 & Sun 6 September',
    location: 'Strijkviertel, Utrecht',
    stagesHeader: 'Stages',
    upNext: 'Up next',
    favHeader: 'Your favorites',
    noFavs: 'No favorites yet. Tap a heart to follow acts.',
    saturday: 'Saturday', sunday: 'Sunday',
    now: 'Now',
    startsIn: 'Starts in',
    notify: 'Reminder for',
    legend: 'Legend',
    entrance: 'Entrance / Exit', toilet: 'Toilet', food: 'Food & Drink',
    firstaid: 'First Aid', info_pt: 'Info', lockers: 'Lockers', water: 'Water', smoke: 'Smoking area',
    faq: 'FAQ',
    contact: 'General & contact',
    reach: 'Getting here',
    lockers_h: 'Lockers',
    golden: 'Golden-GLU',
    min: 'min', hour: 'h',
    favAdded: 'Added to favorites',
    notifOn: 'Notifications on: 15, 10 and 5 min before',
    backToLineup: 'Back to line-up',
    readMore: 'Read more',
    watchClip: 'Watch clip',
    stage: 'Stage', genre: 'Genre', time: 'Time', duration: 'Duration',
  },
};

// Floorplan markers — positions on a 100×50 canvas, roughly matching the festival map
const MARKERS = [
  { id: 'ponton', kind: 'stage', label: 'Ponton', num: '1', x: 22, y: 52 },
  { id: 'lake', kind: 'stage', label: 'The Lake', num: '2', x: 58, y: 58 },
  { id: 'club', kind: 'stage', label: 'The Club', num: '3', x: 78, y: 42 },
  { id: 'hangar', kind: 'stage', label: 'Hangar', num: '4', x: 88, y: 62 },
  { id: 'ent', kind: 'entrance', label: 'Entree', x: 8, y: 38 },
  { id: 'ent2', kind: 'entrance', label: 'Uitgang', x: 94, y: 30 },
  { id: 't1', kind: 'toilet', x: 30, y: 72 },
  { id: 't2', kind: 'toilet', x: 66, y: 32 },
  { id: 't3', kind: 'toilet', x: 82, y: 70 },
  { id: 'f1', kind: 'food', x: 36, y: 40 },
  { id: 'f2', kind: 'food', x: 70, y: 74 },
  { id: 'f3', kind: 'food', x: 48, y: 28 },
  { id: 'i1', kind: 'info', x: 14, y: 60 },
  { id: 'fa1', kind: 'firstaid', x: 40, y: 68 },
  { id: 'l1', kind: 'lockers', x: 12, y: 48 },
  { id: 'w1', kind: 'water', x: 52, y: 48 },
  { id: 'w2', kind: 'water', x: 84, y: 30 },
  { id: 's1', kind: 'smoke', x: 44, y: 78 },
];

Object.assign(window, { STAGES, ACTS, SCHEDULE, I18N, MARKERS });
